#//
#// Copyright 2024 Tobias Strauch, Munich, Bavaria
#// Licensed under the Apache License, Version 2.0, see LICENSE for details.
#// SPDX-License-Identifier: Apache-2.0
#//

MRPHS_D:
	cd execute ;\
	make MRPHS_D

doxygen:
	cd ../doxygen/work ;\
	doxygen Doxyfile

